version: '2'
services:
  maven:
    image: 'mavenjdk8'
    ports:
      - '5000:5000'
    volumes:
      - './:/home/src'
      - maven_repository:/root/.m2/repository
    depends_on:
      - postgresql
    links:
      - postgresql:db
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/example?user=example&password=example
  postgresql:
    image: 'postgres:9.5'
    volumes:
      - './schema:/schema'
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
  myadmin:
     image: "dockage/phppgadmin:latest"
     ports:
       - 5002:80
     links:
       - postgresql:db
     environment:
       - PHP_PG_ADMIN_SERVER_HOST=db
       - PHP_PG_ADMIN_SERVER_DEFAULT_DB=example
volumes: 
  maven_repository:
  postgres_data:
